import schedule_trainingController from "../controller/schedule_trainingsController";
import { Router } from "express";


let Schedule_trainingController= new schedule_trainingController();
let schedule_trainingRouter :Router = Router();

schedule_trainingRouter.post("/CreateSchedule_training",Schedule_trainingController.CreateSchedule_training)
schedule_trainingRouter.put("/UpdateSchedule_training/:id",Schedule_trainingController.UpdateSchedule_training)
schedule_trainingRouter.get("/GetAllSchedule_trainings",Schedule_trainingController.GetAllSchedule_trainings)
schedule_trainingRouter.get("/GetAllApprovedSchedule_trainings",Schedule_trainingController.GetAllApprovedSchedule_training)
schedule_trainingRouter.get("/GetAllRefusedSchedule_tranings",Schedule_trainingController.GetAllRefusedSchedule_tranings)
schedule_trainingRouter.get("/GetAllRejectedSchedule_tranings",Schedule_trainingController.GetAllRejectedSchedule_tranings)
schedule_trainingRouter.get("/GetAllCompletedSchedule_tranings",Schedule_trainingController.GetAllCompletedSchedule_tranings)
schedule_trainingRouter.get("/GetSchedule_trainingById/:id",Schedule_trainingController.GetSchedule_trainingById)
schedule_trainingRouter.get("/GetSchedule_trainingBycompany_id",Schedule_trainingController.GetSchedule_trainingBycompany_id)
schedule_trainingRouter.get("/GetSchedule_trainingByTrainingId",Schedule_trainingController.GetSchedule_trainingByTrainingId)
schedule_trainingRouter.delete("/DeleteSchedule_training/:id",Schedule_trainingController.DeleteSchedule_training)
schedule_trainingRouter.delete("/BulkDeleteSchedule_trainings",Schedule_trainingController.BulkDeleteSchedule_trainings)

export default schedule_trainingRouter